# Generated by Django 5.2.1 on 2025-05-08 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agenda",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                ("data", models.DateField(blank=True, db_column="Data", null=True)),
                ("hora", models.TimeField(blank=True, db_column="Hora", null=True)),
            ],
            options={
                "db_table": "Agenda",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True, db_column="Email", max_length=255, null=True
                    ),
                ),
                (
                    "senha",
                    models.CharField(
                        blank=True, db_column="Senha", max_length=255, null=True
                    ),
                ),
                ("tipo", models.TextField(blank=True, db_column="Tipo", null=True)),
            ],
            options={
                "db_table": "Usuario",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Horarios",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "dia_semana",
                    models.CharField(
                        blank=True, db_column="Dia_semana", max_length=7, null=True
                    ),
                ),
                (
                    "horarios",
                    models.TimeField(blank=True, db_column="Horarios", null=True),
                ),
            ],
            options={
                "db_table": "Horarios",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Local",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "nome_local",
                    models.CharField(
                        blank=True, db_column="Nome_local", max_length=255, null=True
                    ),
                ),
                (
                    "endereco",
                    models.CharField(
                        blank=True, db_column="Endereco", max_length=255, null=True
                    ),
                ),
                (
                    "cnpj",
                    models.CharField(
                        blank=True, db_column="CNPJ", max_length=255, null=True
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, db_column="Telefone", max_length=16, null=True
                    ),
                ),
            ],
            options={
                "db_table": "Local",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Servicos",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="ID", primary_key=True, serialize=False),
                ),
                (
                    "nome",
                    models.CharField(
                        blank=True, db_column="Nome", max_length=255, null=True
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        blank=True, db_column="Descricao", max_length=255, null=True
                    ),
                ),
                (
                    "preco",
                    models.DecimalField(
                        blank=True,
                        db_column="Preco",
                        decimal_places=2,
                        max_digits=5,
                        null=True,
                    ),
                ),
            ],
            options={
                "db_table": "Servicos",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Barbeiro",
            fields=[
                (
                    "id",
                    models.OneToOneField(
                        db_column="ID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="Projeto.usuario",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        blank=True, db_column="Nome", max_length=255, null=True
                    ),
                ),
                (
                    "cpf",
                    models.CharField(
                        blank=True, db_column="CPF", max_length=14, null=True
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, db_column="Telefone", max_length=16, null=True
                    ),
                ),
                (
                    "data_nascimento",
                    models.DateField(
                        blank=True, db_column="Data_Nascimento", null=True
                    ),
                ),
                (
                    "cidade",
                    models.CharField(
                        blank=True, db_column="Cidade", max_length=255, null=True
                    ),
                ),
            ],
            options={
                "db_table": "Barbeiro",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Cliente",
            fields=[
                (
                    "id",
                    models.OneToOneField(
                        db_column="ID",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        primary_key=True,
                        serialize=False,
                        to="Projeto.usuario",
                    ),
                ),
                (
                    "cpf",
                    models.CharField(
                        blank=True, db_column="CPF", max_length=14, null=True
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        blank=True, db_column="Nome", max_length=255, null=True
                    ),
                ),
                (
                    "cidade",
                    models.CharField(
                        blank=True, db_column="Cidade", max_length=255, null=True
                    ),
                ),
                (
                    "telefone",
                    models.CharField(
                        blank=True, db_column="Telefone", max_length=16, null=True
                    ),
                ),
                (
                    "data_nascimento",
                    models.DateField(
                        blank=True, db_column="Data_Nascimento", null=True
                    ),
                ),
            ],
            options={
                "db_table": "Cliente",
                "managed": False,
            },
        ),
    ]
