# Generated by Django 5.2 on 2025-06-09 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('data', models.DateField(blank=True, db_column='Data', null=True)),
                ('hora', models.TimeField(blank=True, db_column='Hora', null=True)),
                ('google_calendar_event_id', models.CharField(blank=True, db_column='GoogleCalendarEventID', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Agenda',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, db_column='Email', max_length=255, null=True)),
                ('senha', models.CharField(blank=True, db_column='Senha', max_length=255, null=True)),
                ('tipo', models.TextField(blank=True, db_column='Tipo', null=True)),
            ],
            options={
                'db_table': 'Usuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('dia_semana', models.CharField(blank=True, db_column='Dia_semana', max_length=7, null=True)),
                ('hora_inicio', models.TimeField(blank=True, db_column='Hora_inicio', null=True)),
                ('hora_fim', models.TimeField(blank=True, db_column='Hora_fim', null=True)),
            ],
            options={
                'db_table': 'Horarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome_local', models.CharField(blank=True, db_column='Nome_local', max_length=255, null=True)),
                ('endereco', models.CharField(blank=True, db_column='Endereco', max_length=255, null=True)),
                ('cnpj', models.CharField(blank=True, db_column='CNPJ', max_length=255, null=True)),
                ('telefone', models.CharField(blank=True, db_column='Telefone', max_length=16, null=True)),
            ],
            options={
                'db_table': 'Local',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=255, null=True)),
                ('descricao', models.CharField(blank=True, db_column='Descricao', max_length=255, null=True)),
                ('preco', models.DecimalField(blank=True, db_column='Preco', decimal_places=2, max_digits=5, null=True)),
                ('duracao', models.IntegerField(blank=True, db_column='Duracao', null=True)),
            ],
            options={
                'db_table': 'Servicos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Barbeiro',
            fields=[
                ('id', models.OneToOneField(db_column='ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Barba_e_Navalha.usuario')),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=255, null=True)),
                ('cpf', models.CharField(blank=True, db_column='CPF', max_length=14, null=True)),
                ('telefone', models.CharField(blank=True, db_column='Telefone', max_length=16, null=True)),
                ('data_nascimento', models.DateField(blank=True, db_column='Data_Nascimento', null=True)),
                ('cidade', models.CharField(blank=True, db_column='Cidade', max_length=255, null=True)),
            ],
            options={
                'db_table': 'Barbeiro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.OneToOneField(db_column='ID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Barba_e_Navalha.usuario')),
                ('cpf', models.CharField(blank=True, db_column='CPF', max_length=14, null=True)),
                ('nome', models.CharField(blank=True, db_column='Nome', max_length=255, null=True)),
                ('cidade', models.CharField(blank=True, db_column='Cidade', max_length=255, null=True)),
                ('telefone', models.CharField(blank=True, db_column='Telefone', max_length=16, null=True)),
                ('data_nascimento', models.DateField(blank=True, db_column='Data_Nascimento', null=True)),
            ],
            options={
                'db_table': 'Cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GoogleApiToken',
            fields=[
                ('barbeiro', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Barba_e_Navalha.barbeiro')),
                ('token', models.CharField(max_length=255)),
                ('refresh_token', models.CharField(blank=True, max_length=255, null=True)),
                ('token_uri', models.CharField(max_length=255)),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.CharField(max_length=255)),
                ('scopes', models.TextField()),
            ],
            options={
                'db_table': 'GoogleApiToken',
                'managed': True,
            },
        ),
    ]
