# Generated by Django 5.2.1 on 2025-06-13 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Gestao_Agendamento", "0001_initial"),
        ("Login_Autenticacao", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Agenda",
        ),
        migrations.RemoveField(
            model_name="barbeiro",
            name="id",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="id",
        ),
        migrations.DeleteModel(
            name="Horarios",
        ),
        migrations.DeleteModel(
            name="Local",
        ),
        migrations.DeleteModel(
            name="Servicos",
        ),
        migrations.DeleteModel(
            name="Usuario",
        ),
        migrations.AlterField(
            model_name="googleapitoken",
            name="barbeiro",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="Login_Autenticacao.barbeiro",
            ),
        ),
        migrations.DeleteModel(
            name="Barbeiro",
        ),
        migrations.DeleteModel(
            name="Cliente",
        ),
    ]
