# Generated by Django 5.2.1 on 2025-05-19 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Gestao_Agendamento", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="usuario",
            table="",
        ),
    ]
