# Generated by Django 5.2.1 on 2025-06-06 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Gestao_Agendamento", "0002_alter_usuario_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="usuario",
            table="Usuario",
        ),
    ]
