# Generated by Django 5.2.1 on 2025-06-06 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Gestao_Agendamento", "0003_alter_usuario_table"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Agenda",
        ),
        migrations.RemoveField(
            model_name="barbeiro",
            name="id",
        ),
        migrations.RemoveField(
            model_name="cliente",
            name="id",
        ),
        migrations.DeleteModel(
            name="Horarios",
        ),
        migrations.DeleteModel(
            name="Local",
        ),
        migrations.DeleteModel(
            name="Servicos",
        ),
        migrations.DeleteModel(
            name="Barbeiro",
        ),
        migrations.DeleteModel(
            name="Cliente",
        ),
        migrations.DeleteModel(
            name="Usuario",
        ),
    ]
